{
 "title": "Wonju Passivhaus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "v_firmware_version", "label": "C6M Firmware", "query": { "query": "label_values(firmware_version)" } },
   {
    "name": "v_panel_firmware_version",
    "label": "Panel Firmware Version",
    "query": {
     "query": "label_values(panel_firmware_version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Komfovent Ventilation Unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Power"
    },
    {
     "expr": "eco{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Eco Mode"
    },
    {
     "expr": "auto{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Auto Mode"
    }
   ]
  },
  {
   "title": "Icon",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "status_icon_fan{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Fan"
    },
    {
     "expr": "status_icon_rotor{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Rotor"
    },
    {
     "expr": "status_icon_heating{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heating"
    },
    {
     "expr": "status_icon_cooling{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Cooling"
    }
   ]
  },
  {
   "title": "Mode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "current_mode{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Current Mode"
    }
   ]
  },
  {
   "title": "Supply Fan Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "supply_flow{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Supply Flow (%)"
    },
    {
     "expr": "supply_fan_sntensivity{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Actual Supply Flow (%)"
    },
    {}
   ]
  },
  {
   "title": "Extract Fan Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "extract_flow{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Extract Flow (%)"
    },
    {
     "expr": "extract_fan_sntensivity{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Extract Supply Flow (%)"
    }
   ]
  },
  {
   "title": "Energy Counter (Day)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahu_consumption_day{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Consumed Energy (Wh)"
    },
    {
     "expr": "additional_air_heater_consumption_day{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heating Energy (Wh)"
    },
    {
     "expr": "recovered_energy_day{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Recovered Energy (Wh)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "supply_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Supply Temperature (°C)"
    },
    {
     "expr": "extract_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Extract Temperature (°C)"
    },
    {
     "expr": "outdoor_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Outdoor Temperature (°C)"
    },
    {
     "expr": "panel_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Control Panel Temperature (°C)"
    },
    {
     "expr": "panel_humidity{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Control Panel Humidity (%)"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "normal_setpoint{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Air Temperature - Normal (°C)"
    },
    {
     "expr": "override_setpoint{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Air Temperature - Override (°C)"
    }
   ]
  },
  {
   "title": "Energy Counter (Month)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ahu_consumption_month{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Consumed Energy (Wh)"
    },
    {
     "expr": "additional_air_heater_consumption_month{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heating Energy (Wh)"
    },
    {
     "expr": "recovered_energy_month{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Recovered Energy (Wh)"
    }
   ]
  },
  {
   "title": "Eco Mode Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "free_heating_or_cooling{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Free Heating/Cooling"
    },
    {
     "expr": "heating_enable_denied{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heating Enable Denied"
    },
    {
     "expr": "cooling_enable_denied{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Cooling Enable Denied"
    },
    {
     "expr": "heat_recovery_control{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heat Recovery Control"
    },
    {
     "expr": "minimum_supply_air_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Min Air Supply Temp. (°C)"
    },
    {
     "expr": "maximum_supply_air_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Max Air Supply Temp. (°C)"
    }
   ]
  },
  {
   "title": "SPI",
   "type": "gauge",
   "description": "1CMH의 공기를 공급할 때 소비되는 전력량",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "W/(m3/h)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spi{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"} / 100",
     "legendFormat": "SPI"
    },
    {
     "expr": "spi_per_day{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"} / 100",
     "legendFormat": "SPI per Day"
    }
   ]
  },
  {
   "title": "Efficiency and Comsumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Power Comsumption (W)"
    },
    {
     "expr": "heater_power{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heating Power (W)"
    },
    {
     "expr": "heat_exchanger_recovery{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heat Exchanger Recovery (W)"
    },
    {
     "expr": "heat_exchanger_efficiency{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Heat Exchanger Efficiency (%)"
    },
    {
     "expr": "energy_saving{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Energy Savings (%)"
    }
   ]
  },
  { "title": "Atmocube", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Air Quality #1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voc_index", "legendFormat": "VOC Index" },
    { "expr": "nox_index", "legendFormat": "NOx Index" },
    { "expr": "co2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "Air Quality #2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tvoc", "legendFormat": "TVOC" },
    { "expr": "co", "legendFormat": "CO" },
    { "expr": "o3", "legendFormat": "O3" },
    { "expr": "ch2o", "legendFormat": "Formaldehyde" }
   ]
  },
  {
   "title": "Particle Pollution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm1", "legendFormat": "PM1.0" },
    { "expr": "pm25", "legendFormat": "PM2.5" },
    { "expr": "pm4", "legendFormat": "PM4" },
    { "expr": "pm10", "legendFormat": "PM10" }
   ]
  },
  {
   "title": "Indoor Index #1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "Temperature" },
    { "expr": "humidity", "legendFormat": "Humidity" },
    { "expr": "absolute_humidity", "legendFormat": "Absolute Humidity" }
   ]
  },
  {
   "title": "Indoor Index #2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature", "legendFormat": "LR Temperature (°C)" },
    { "expr": "humidity", "legendFormat": "Humidity (%)" },
    {
     "expr": "outdoor_temperature{job=\"komfovent\", firmware_version=~\"$v_firmware_version\", panel_firmware_version=~\"$v_panel_firmware_version\"}",
     "legendFormat": "Outdoor Temperature (°C)"
    }
   ]
  },
  {
   "title": "Misc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    { "expr": "light", "legendFormat": "Light (Lx)" },
    { "expr": "noise", "legendFormat": "Noise (dB)" },
    { "expr": "pressure", "legendFormat": "Pressure (mbar)" }
   ]
  }
 ]
}